### ISSUE TITLE
Make interrupting a property of the bthread, not only of the bsync

### ISSUE THREAD

**Issue by geraw** [bThink-BGU/BPjs#105]

**Comment by michbarsinai** [comment]
Need to discuss this. Can this be replaced with a synchronization statement stack on the `bp` object?

**Comment by geraw** [comment]
I think that this can be implemented easily as an add-on to BPjs given that users can attach data objects to their b-threads. Specifically, users can use their own `bp.sync` function that adds the interrupting part seamlessly.

**Comment by michbarsinai** [comment]
Implemented as @geraw suggested.
