### ISSUE TITLE
Use Rhino Debugger to extract ContinuationProgramState

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#110]
The use of reflection is no longer needed, as Rhino Debugger contains all the required data - https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino/Debugger

**Comment by michbarsinai** [comment]
Hopefully, reflection will be replaced by the code written by Attila. That code is now part of Rhino too, and also works directly in the continuation object (https://github.com/mozilla/rhino/pull/453). So should be more performant.
