### ISSUE TITLE
JS Set toString

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#135]
JS Set is not printed correctly. Consider the following code:
```javascript
let s = new Set()
s.add(1)
bp.sync({request: bp.Event("a", s)})
bp.log.info(s)
```
The following lines are printed when the code is executed:
[BEvent name:a data:{}]
[BP][Info] {}

**Comment by michbarsinai** [comment]
Ongoing. It's unclear how to iterate over set members from Java.

https://stackoverflow.com/questions/65517881/accessing-nativeset-members-in-mozilla-rhino-from-java

**Comment by michbarsinai** [comment]
Found a workaround using JS. Not ideal, but does the job.
