### ISSUE TITLE
bp.store and bp.thread.data do not use jsEquals

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#144]

**Comment by michbarsinai** [comment]
Extending this a bit to include `hashCode` and recursion through collections (`Map<?,ScriptableObject>`).

**Comment by michbarsinai** [comment]
11 files changed for this one, but lots of mysteries solved 😄. Nice catch, @eggsterino !

**Comment by eggsterino** [comment]
Dirty thing. Took me a few days only to realize that the bug is not in my code, and another couple to track it down 😖

Anyway, I think there is still a problem, though I am not sure because I only read your changes and didn't run it...

jsEquals doesn't call jsSetEquals (actually no one does, except for the tests). Also, I think it would be better to check is jsEquals for Set, Map, and Collection, in this order. Collection is more general.
