### ISSUE TITLE
Add ContinueAfterViolation flag to DfsBProgramVerifier

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#156]
When doing state mapping using dfs - the dfs halts on violation. It would be nice to add a flag that continues the dfs even when a violation is found (of course the violating node should be popped from the stack).

This flag also makes sense when we wish to find many violation in one run, and not only one.

**Comment by michbarsinai** [comment]
I think a similar functionality is here, where the verification listener can decide whether to continue or not based on the violation found:

https://github.com/bThink-BGU/BPjs/blob/develop/src/main/java/il/ac/bgu/cs/bp/bpjs/analysis/DfsBProgramVerifier.java#L103

Might need to update the documentation, though.

**Comment by michbarsinai** [comment]
Documented.
