### ISSUE TITLE
Is it possible to redirect `bp.log.info` output?

### ISSUE THREAD

**Issue by ZvikaZ** [bThink-BGU/BPjs#163]
Hi.

Is it possible to redirect `bp.log.info` output?
Something similar to event redirection:

            PrintStream ps = new PrintStream(bpRunLog);
            rnr.addListener( new PrintBProgramRunnerListener(ps) );

If it's not possible, it'd be great to have this feature.

**Comment by michbarsinai** [comment]
It's coming in the next version, thanks to this PR (already merged to develop).

https://github.com/bThink-BGU/BPjs/pull/159

**Comment by michbarsinai** [comment]
There’s no planned schedule yet. If all test pass, I can create an update release later this week.

**Comment by ZvikaZ** [comment]
Thanks
