### ISSUE TITLE
No Context.exit() in BPjs.makeBPjsSubScope()

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#176]
https://github.com/bThink-BGU/BPjs/blob/e6932e2ac3bd3ebf3922dc83827c2a8979bbe403/src/main/java/il/ac/bgu/cs/bp/bpjs/BPjs.java#L91

**Comment by eggsterino** [comment]
See comment at https://github.com/bThink-BGU/BPjs/commit/76d20be3479e271582752d78759e1fca877c93c9#r66831363

**Comment by michbarsinai** [comment]
Implemented there.
