### ISSUE TITLE
Add initial verification CLI

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#18]
So users can validate from the command line, not just from Java programs.

**Comment by acepace** [comment]
Doesn't this already exist in [BPJsCliRunner.java](https://github.com/bThink-BGU/BPjs/blob/develop/src/main/java/il/ac/bgu/cs/bp/bpjs/mains/BPJsCliRunner.java) or do you want a richer CLI?

**Comment by michbarsinai** [comment]
Richer CLI, possibly adding a debugger, program composer (e.g. load f1, load f2, load f3, verify). On the other hand, while we're still keeping everything in the core library, we don't want too many dependencies. Eventually the CLI will just be another application that depends on the core library.

**Comment by michbarsinai** [comment]
Implemented in
