### ISSUE TITLE
Automatic event conversion

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#5]
In BThreadJSProxy, we can allow a shorthand where users pass just the name of the event and we generate the event for it. So the following lines of code are equivalent:

```javascript
bsync({request:"A"});
bsync({request:bp.Event("A")});
```

Can also consider allowing a to-stringed integer. Other objects there should result in `IllegalArgumentException`.

**Comment by michbarsinai** [comment]
OK, maybe this is a bad idea as it allows bad habits:

1. works against event object reuse
2. prone to typos

Need to let the community decide on this.

**Comment by acepace** [comment]
Problem is making it hard to pass in a collection of events, what's the equivalent? collection of strings?

**Comment by michbarsinai** [comment]
Well, that would be consistent, I guess.

```
bp.sync({request:[bp.Event("Tic", {meta:"data"}), "Tac"], block:"Toe"})
```

**Comment by michbarsinai** [comment]
There's also the "kitchen sink" approach, were we can register converter functions somewhere. Such function can either return a false-y value (`null`, `undefined`, et. al) or an event. Something along these lines:

```javascript
bp.registerEventConvertor( function(v) {
   if ( typeof(v) === "String" ) return bp.Event(v);
});
bp.registerEventConvertor( function(v) {
   if ( Array.isArray(v) && v.length==3 ) return bp.Event(v[0], {x:v[1], y:v[2]});
});
```

Might be an overkill, but would allow a more relaxed programming style. We can then get some default converters as well (the string->event one, probably). It could also be used to fire oneself in the leg, or course, but I think that's an advanced feature and so people know they should beware when using it.

**Comment by eggsterino** [comment]
I am in favor of the "kitchen sink" approach. These converters can be disabled by default (and allow to enable them through the configuration file). This way we will be able to provide alerts to the user.

**Comment by michbarsinai** [comment]
We need to also consider reuse here. If one team converts `"A"` to `EventA("A")` and another team converts `"A"` to `EventB("A")`, they can't mix b-thread code. Somewhat similar to SmallTalk's monkey-patching that also gave some serious grief to Objective-C.

**Comment by michbarsinai** [comment]
Closing this... automatic conversion created too much ambiguities (see C++ `explicit`, and Scala's `implicit`). And anyway, people tend to create utility functions in JS:

```javascript
function e(str){
   return bp.Event(str, {lib:"myLib", miceCount:STR_TO_MICE[str]);
}

...
bp.sync({request(e("micky")});

```
