### ISSUE TITLE
PrioritizedBThreadsEventSelectionStrategy does not support empty lists

### ISSUE THREAD

**Issue by geraw** [bThink-BGU/BPjs#70]
An exception is raised when the list of requested and not blocked events is empty.

**Comment by eggsterino** [comment]
The fix created another bug - external events are now missed.
Due to line 74 in this commit (8a0801a): 
`if ( requestedAndNotBlockedWithPriorities.isEmpty() ) {
    return Collections.
}`
If there are statements but all requested are blocked - the code will not reach this check at the end of the method.
