### ISSUE TITLE
NullPointerException PrioritizedBSyncEventSelectionStrategy

### ISSUE THREAD

**Issue by eggsterino** [bThink-BGU/BPjs#83]
In commit b43bca4 , line 72:
`OptionalInt maxValueOpt = statements.stream()
                                            .filter( s -> !getRequestedAndNotBlocked(s, blocked).isEmpty() )
                                            .mapToInt(this::getValue)
                                            .max();`
No `.filter( stmt -> stmt!=null )`

Which may lead to a NullPointerException (didn't test it).

**Comment by michbarsinai** [comment]
`getRequestedAndNotBlocked` always returns a `Set`. That might be an empty set, but it's never `null` (created via `stream().....collect(toSet())`.
