### ISSUE TITLE
Request: Remove printout

### ISSUE THREAD

**Issue by michbarsinai** [bThink-BGU/BPjs#90]
Hi,

Can you remove this annoying printout?:

if (!cn.startsWith("java.") && !cn.startsWith("il.ac.bgu")) {
    System.out.println("collectJsValue: blind translation to java: " + jsValue + " (" + jsValue.getClass() + ")");
}

(Line #118 in ContinuationProgramState)

**Comment by geraw** [comment]
Does this mean that verification assumes a one-to-one correspondence between the toString of these objects and the objects themselves?

I am trying to verify a program with java events that are stored in the b-threads. Is it safe to do this? Is it enough if I keep the toString of these objects informative?

**Comment by michbarsinai** [comment]
No, it should be fine as long as you have state-based `equals` and `hashCode` on your Java events.

**Comment by geraw** [comment]
What is the default state comparison for `BEvent`?

**Comment by michbarsinai** [comment]
Name, and data object (if exists).

https://github.com/bThink-BGU/BPjs/blob/develop/src/main/java/il/ac/bgu/cs/bp/bpjs/model/BEvent.java#L97

Note the use of `jsEquals` there. It's intended to bypass the fact that Rhino uses `ConsString` and not `java.lang.String`. Other than that it 

* jsEquals: https://github.com/bThink-BGU/BPjs/blob/aaba419d29cfac062c0f7ced81eb190d02087e40/src/main/java/il/ac/bgu/cs/bp/bpjs/internal/ScriptableUtils.java#L71
* jsScriptableObjectEquals: https://github.com/bThink-BGU/BPjs/blob/aaba419d29cfac062c0f7ced81eb190d02087e40/src/main/java/il/ac/bgu/cs/bp/bpjs/internal/ScriptableUtils.java#L95
