### ISSUE TITLE
Does BPjs verifiyer supports dynamic creation of b-threads:

### ISSUE THREAD

**Issue by geraw** [bThink-BGU/BPjs#92]

**Comment by geraw** [comment]
`bp.registerBThread('my_bt', function () {
    var c = 0;
    while (true) {
        application= bp.sync({waitFor: AnyMinimalEvent});
        bp.registerBThread('triggered_bt-' + (c++), function () {
            bp.sync({request: A})
            bp.sync({request: B})
            bp.sync({request: C})
        });
    }
});
`

**Comment by michbarsinai** [comment]
Yes :-)
